#! /bin/bash

COLOR='\e[0;32m'
STATUS_COLOR='\e[0;32m'
ERROR_COLOR='\e[0;31m'
NC='\e[0m'

echo_Status () {
	echo -e "${STATUS_COLOR}${1}${NC}"
}

echo_Error () {
	echo -e "${ERROR_COLOR}${1}${NC}"
}

######INITIALIZATION CODE = Derive/validate paths.
folder_mongo_root=`sudo which mongod`
if [ "${folder_mongo_root}" = "" ] #Check mongod was found
then
	echo_Error"Could not find location of mongod"
	exit 1
else
	folder_mongo_root=${folder_mongo_root%\/mongod}
fi

######INITIALIZATION CODE ends

##### STOPPING historicalTweets.py
echo_Status "Checking for running instance of historicalTweets.py"
historicalTweets_running=`pgrep -f historicalTweets.py | wc -l`
if [[ $historicalTweets_running == 0 ]]
then  	echo_Status "historicalTweets.py is not running"
	echo_Status "Proceeding with execution..."
else	echo_Status "Running instance of historicalTweets.py detected."
	echo_Status "Killing existing instance..."
	pgrep -f historicalTweets.py | xargs kill
fi
echo_Status "Historical Tweets instance killed"
##### STOPPING historicalTweets.py ends

##### STOPPING crisisServer.py
echo_Status "Checking for running instance of crisisSever"
crisisServer_running=`pgrep -f crisisServer.py | wc -l`
if [[ $crisisServer_running == 0 ]]
then  	echo_Status "crisisServer is not running"
	echo_Status "Proceeding with execution..."
else	echo_Status "Running instance of crisisServer detected."
	echo_Status "Killing existing instance..."
	pgrep -f crisisServer.py | xargs kill
fi
echo -e "${COLOR}Crisis Server instance killed."
##### STOPPING crisisServer.py ends

###### STOP MONGOD
echo_Status "Checking for running instance of Mongo DB server."
mongod_running=`pgrep -f mongod | wc -l`
if [[ $mongod_running == 0 ]]
then  	echo_Status "Mongo DB server is not running"
	echo_Status "Proceeding with execution..."
else	echo_Status "Running instance of Mongo DB server detected."
#	sudo ${folder_mongo_root}/bin/mongod --shutdown
	mongo << EOF
use admin
db.shutdownServer()
exit
EOF
	echo_Status "Stopped Mongo DB server"
fi
###### STOP MONGOD ends

rm -f nohup.out
